create database Recuperação;
use Recuperação;

-- Exercicio 2
CREATE TABLE CLIENTE (
  idCLIENTE INTEGER PRIMARY KEY,
  nomeCLIENTE VARCHAR(30) NOT NULL,
  RG_CLIENTE VARCHAR(20) NOT NULL
);

CREATE TABLE VENDEDOR (
  idVENDEDOR INTEGER PRIMARY KEY,
  nomeVENDEDOR VARCHAR(45) NOT NULL
);

CREATE TABLE PEDIDO (
  numPEDIDO INTEGER PRIMARY KEY,
  DataPedido DATETIME NOT NULL,
  ValorPedido NUMERIC(10,2) NOT NULL,
  VENDEDOR_idVENDEDOR INTEGER NOT NULL,
  CLIENTE_idCLIENTE INTEGER NOT NULL,
  FOREIGN KEY (VENDEDOR_idVENDEDOR) REFERENCES VENDEDOR(idVENDEDOR),
  FOREIGN KEY (CLIENTE_idCLIENTE) REFERENCES CLIENTE(idCLIENTE)
);

-- Exercicio 3

CREATE TABLE fFORNECEDOR (
  idFORNECEDOR INTEGER PRIMARY KEY,
  nomeFORNECEDOR VARCHAR(45) NOT NULL
);

CREATE TABLE fPRINCIPIOATIVO (
  idPRINCIPIOATIVO INTEGER PRIMARY KEY,
  nomePRINCIPIOATIVO VARCHAR(60) NOT NULL
);

CREATE TABLE fMEDICAMENTO (
  idMEDICAMENTO INTEGER,
  NomeComercial VARCHAR(60) NOT NULL,
  QtdeEstoque INTEGER NOT NULL,
  idPRINCIPIOATIVO_FK INTEGER NOT NULL,
  idFORNECEDOR_FK INTEGER NOT NULL,
  PRIMARY KEY (idMEDICAMENTO),
  FOREIGN KEY (idPRINCIPIOATIVO_FK) REFERENCES fPRINCIPIOATIVO(idPRINCIPIOATIVO),
  FOREIGN KEY (idFORNECEDOR_FK) REFERENCES fFORNECEDOR(idFORNECEDOR)
);




